[build]
  command = "yarn build"
  publish = "dist"
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = false
  minify = true
[build.processing.js]
  bundle = false
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = false
[[redirects]]
  from = "/github"
  to = "https://github.com/whizkydee"
  status = 301
  force = true
[[redirects]]
  from = "/twitter"
  to = "https://twitter.com/mrolaolu"
  status = 301
  force = true
[[redirects]]
  from = "/music"
  to = "https://soundcloud.com/kitanmusic"
  status = 301
  force = true
[[redirects]]
  from = "/palenight"
  to = "https://marketplace.visualstudio.com/items?itemName=whizkydee.material-palenight-theme"
  status = 301
  force = true
[[redirects]]
  from = "/palenight-repo"
  to = "https://github.com/whizkydee/vscode-palenight-theme"
  status = 301
  force = true
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
